# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c5da632c94f15b0ea1b3fb750d010cf63714c2381fe83181b353461cbc3a79539c716153eb76422fcb1dfd675553197741ce7b4b7e154d02737c110f57e64c8

test:
  secret_key_base: 35a47ff60eb47ed7f0341f95397ee647d7b4ea271a603c7f65cc8b8045db829b7247efee6c6f7a0f17eed9d4f8d461387e4d8f974ae2f417c087c69dbaca519a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
